# Generated by Django 3.2.12 on 2023-08-12 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
